
project_id = "kshciumqqwvbaicdlzkz"

[functions.send-notification]
verify_jwt = true
import_map = "./import_map.json"

[functions.store-subscription]
verify_jwt = true
import_map = "./import_map.json"

[functions.remove-subscription]
verify_jwt = true
import_map = "./import_map.json"

[functions.create-rpc]
verify_jwt = true
import_map = "./import_map.json"
